config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  authenticated :user do
    root to: "dashboards#dashboard", as: "authenticated_root"
  end
  unauthenticated :user do
    root to: "pages#home"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :consumptions, only: [:new, :create] do
    resources :cigarettes, only: [:create]
  end
  get '/login', to: 'pages#login', as: 'login'
  get '/simulation', to: 'pages#simulation', as: 'simulation'
  get '/result', to: 'pages#result', as: 'result'
  get '/objective/new', to: 'pages#new_objective', as: 'new_objective'
  post '/objective/create', to: 'pages#create_objective', as: 'create_objective'
  get '/objective/show', to: 'pages#show_objective', as: 'show_objective'
  get '/dashboard', to: 'dashboards#dashboard', as: 'dashboard'
  get '/dashboard/pot', to: 'dashboards#pot', as: 'dashboard_pot'
  get '/dashboard/health', to: 'dashboards#health', as: 'dashboard_health'
  get '/dashboard/motivation', to: 'dashboards#motivation', as: 'dashboard_motivation'
  # get '/dashboard/new_transaction', to: 'dashboards#new_transaction', as: 'dashboard_new_transaction'
  # post '/dashboard/new_transaction', to: 'dashboards#create_new_transaction', as: 'dashboard_create_new_transaction'
  resources :transactions, only: [:new, :create]
  get '/profile', to: 'profiles#profile_home', as: 'profile_home'
  get '/profile/edit/profile_info', to: 'profiles#profile_info', as: 'profile_info'
  # edit_user_registration GET    /users/edit(.:format)

  # user_registration PATCH  /users(.:format)
  get '/profile/edit/profile_bank', to: 'profiles#edit_profile_bank', as: 'profile_bank'
  patch '/profile/edit/profile_bank', to: 'profiles#update_profile_bank'
  #consumptions POST   /consumptions(.:format) consumptions#create
  # new_consumption GET    /consumptions/new(.:format) consumptions#new
  get '/get_my_pot', to: 'profiles#recover_my_pot', as: 'recover_my_pot'
  patch '/get_my_pot', to: 'profiles#withdraw', as: 'withdraw'
  get '/profile/edit/avatar', to: 'profiles#avatar_base', as: 'avatar'
  patch '/profile/edit/avatar', to: 'profiles#avatar', as: 'update_avatar'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def profile_home
  end

  def profile_info
  end

  def edit_profile_bank
    @consumption = Consumption.find_by(user: current_user)
  end

  def update_profile_bank
    current_user.iban = params[:iban]
    if current_user.save
      redirect_to profile_home_path
    else
      render :edit_profile_bank
    end
  end

  def recover_my_pot
  end

  def withdraw
  end

  def avatar_base
  end

  def avatar
    current_user.photo = params[:photo]
    if current_user.save
      redirect_to profile_home_path
    else
      render :edit_avatar
    end
  end
end

app/views/profiles/avatar.html.erb
<div class="container">

      <div class="back-arrow">
        <%= link_to profile_home_path, id: "icone-arrow" do %>
              <i class="iconify" data-icon="akar-icons:arrow-left"></i>
            <% end %>
      </div>

      <div class="profile-info">
        <h1>Modifier ma photo de profil</h1>
        <div class ="icone-profile">
            <span class="iconify" data-icon="carbon:user-avatar"></span>
        </div>
      </div>

    <%# <div>
      <p>Pas satisfait? <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %>
</div>

app/views/profiles/avatar_base.html.erb
<div class="container">

      <div class="back-arrow">
        <%= link_to profile_home_path, id: "icone-arrow" do %>
          <i class="iconify" data-icon="akar-icons:arrow-left"></i>
         <% end %>
      </div>

      <div class="profile-info">
        <h1>Modifier ma photo de profil</h1>
        <br>
        <br>
        <div class ="icone-profile">
            <%= link_to avatar_path, id: "icone-arrow" do %>
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, height: 120, width: 120, crop: :fill, class: "rounded-circle" %>
              <% else %>
                <%= image_tag "https://eu.ui-avatars.com/api//?name=#{current_user.first_name}+#{current_user.last_name}&background=06C4BE&color=00586B",  height: 120, width: 120, crop: :fill, class: "rounded-circle" %>
              <% end %>
            <% end %>
        </div>
      </div>


<br>
<br>




        <div class="form-input-with">
          <%= form_with url: update_avatar_path, method: :patch do |f| %>
            <%= f.file_field :photo %>
            <br>
            <br>
            <br>
            <div class="form-action-with">
              <%= f.submit "Valider", class:"green-btn" %>
            </div>
          <% end %>
        </div>




    <%# <div>
      <p>Pas satisfait? <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %>
</div>

app/views/profiles/edit_profile_bank.html.erb
<div class="container">

      <div class="back-arrow">
        <%= link_to profile_home_path, id: "icone-arrow" do %>
              <i class="iconify" data-icon="akar-icons:arrow-left"></i>
            <% end %>
      </div>

      <div class="profile-info">
        <h1>Mes informations bancaires</h1>
        <div class ="icone-profile">
          <span class="iconify" data-icon="akar-icons:wallet"></span>
        </div>
        <%# <h2>Edit <%= resource_name.to_s.humanize %></h2>
        <div class="user-name">
          <%= current_user.first_name %>
          <%= current_user.last_name %>
        </div>
      </div>

      <div class="iban-update">
        <div class="form-input-with">
          <%= form_with url: profile_bank_path, method: :patch do |f| %>
            <%= f.label :query, "Nom de votre banque:" %>
          <div class="form-with-control-empty">
            <%= f.text_field :bank_name, value: "Caisse d'Epargne" %>
          </div>
            <%= f.label :query, "Votre IBAN:" %>
          <div class="form-with-control-empty">
            <%= f.text_field :iban, required: 'required', class: "iban-form",  value: "FR1420041010050500013M02606"%>
          </div>

        <br>
        <br>
        <br>
            <div class="form-action-with">
              <button class="green-btn submit-iban">Valider</button>
              <%= render "shared/modal_confirmation", f: f, consumption: @consumption %>
          <% end %>
          </div>
                        <% if current_user.errors[:iban].any? %>
                          <% current_user.errors[:iban].each do %>
                            <%= "Merci de renseigner un IBAN valide" %>
                          <% end %>
                        <% end %>
        </div>


      </div>

  <script type="text/javascript" charset="utf-8">
      let elements = document.querySelector(".submit-iban")
      console.log(elements)
      elements.addEventListener("click", (event) => {
          event.preventDefault()
          showModal()
      })

      let showModal = () => {
          $('#confirmationModal').modal('toggle')
      }
  </script>

    <%# <div>
      <p>Pas satisfait? <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %>
</div>

app/views/profiles/profile_home.html.erb
<div class="container">


       <div class="back-arrow">
        <%= link_to dashboard_path, id: "icone-arrow" do %>
              <i class="iconify" data-icon="akar-icons:arrow-left"></i>
            <% end %>
        <%= link_to destroy_user_session_path, method: :delete, id: "icone-arrow" do %>
              <span class="iconify" data-icon="bx:log-out-circle" data-rotate="180deg"></span>
            <% end %>
      </div>


        <div class="my-profile-h1" >
          <h1>Mon profil</h1>
        </div>


      <div class="profile-card" >

        <div class="profile-card-info">
          <div class ="icone-profile">
            <%= link_to avatar_path, id: "icone-arrow" do %>
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, height: 70, width: 70, crop: :fill, class: "rounded-circle" %>
              <% else %>
                <%= image_tag "https://eu.ui-avatars.com/api//?name=#{current_user.first_name}+#{current_user.last_name}&background=06C4BE&color=00586B", height: 70, width: 70, crop: :fill, class: "rounded-circle" %>
              <% end %>
            <% end %>
          </div>
          <%# <h2>Edit <%= resource_name.to_s.humanize %></h2>
          <div class="user-name-verified">
            <div class="user-name">
              <%= current_user.first_name.capitalize %>
              <%= current_user.last_name.capitalize %>
            </div>
            <div id="nocig-member">
              <p>Membre NoCig vérifié</p>
            </div>
          </div>


          <div class="card-icone">
            <%= link_to edit_user_registration_path, id: "icone-arrow" do %>
              <i class="iconify" data-icon="dashicons:arrow-right-alt2"></i>
            <% end %>
          </div>
        </div>


        <div class="profile-card-iban">
            <p id="iban">Mon IBAN</p>
            <% if current_user.iban %>
            <%= "#{current_user.iban.first(4)}**************#{current_user.iban.last(4)}"  %>
            <% else%>
              <div id="link-bank" <% link_to profile_bank_path%>>
              <p>Ajouter vos informations bancaires</p>
              </div>
            <% end %>
        </div>

      </div>


      <div class="profile-redirect-info">
        <div class="btn btn-grey-info" <% link_to profile_bank_path%>>
          <%= link_to 'Modifier mes données bancaires', profile_bank_path, class:"profile-redirect-info-color"%>
          <span class="iconify" data-icon="dashicons:arrow-right-alt2"></span>
        </div>

        <div class="btn btn-grey-info" <% link_to profile_info_path%>>
          <%= link_to 'Informations personnelles', profile_info_path, class:"profile-redirect-info-color"%>
          <span class="iconify" data-icon="dashicons:arrow-right-alt2"></span>
        </div>

        <div class="btn btn-grey-info" <% recover_my_pot_path%>>
          <%= link_to 'Retirer le montant de ma cagnotte', recover_my_pot_path, class:"profile-redirect-info-color"%>
          <span class="iconify" data-icon="dashicons:arrow-right-alt2"></span>
        </div>

        <div class="btn btn-grey-info">
          <%= link_to 'Suivi de mes transactions', withdraw_path, class:"profile-redirect-info-color"%>
          <span class="iconify" data-icon="dashicons:arrow-right-alt2"></span>
        </div>


      </div>



    <%# <div>
      <p>Pas satisfait? <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %>
</div>

app/views/profiles/recover_my_pot.html.erb
<div class="conso-container">

  <div class="header-pink-motivation">
    <div class="back-arrow">
      <%= link_to 'Back', onclick: "window.history.back();", id: "icone-arrow" do %>
        <i class="iconify" data-icon="akar-icons:arrow-left"></i>
      <% end %>
    </div>
    <h1 id="get-pot-title">Retirer l'argent de ma cagnotte</h1>
  </div>

  <div class="container">

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <i class="iconify iconify-moneyy" data-icon="emojione-monotone:money-with-wings"></i>

    <div id="text-get-pot"><h4>Vous avez </h4></div>


    <div class= "cards-motivation">
        <div class="card-pot">
            <h2 class="card__title-pot"><%= current_user.pot %>€</h2>
        </div>
        <br>
    <div id="text-get-pott"><h4>Disponible sur votre cagnotte</h4></div>
    <br>
    <br>
    <br>
    <br>
    <p class="green-btn" style="text-align:center; padding-top: 5px;">BANKO</button>
  </div>
</div>