config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  authenticated :user do
    root to: "dashboards#dashboard", as: "authenticated_root"
  end
  unauthenticated :user do
    root to: "pages#home"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :consumptions, only: [:new, :create] do
    resources :cigarettes, only: [:create]
  end
  get '/login', to: 'pages#login', as: 'login'
  get '/simulation', to: 'pages#simulation', as: 'simulation'
  get '/result', to: 'pages#result', as: 'result'
  get '/objective/new', to: 'pages#new_objective', as: 'new_objective'
  post '/objective/create', to: 'pages#create_objective', as: 'create_objective'
  get '/objective/show', to: 'pages#show_objective', as: 'show_objective'
  get '/dashboard', to: 'dashboards#dashboard', as: 'dashboard'
  get '/dashboard/pot', to: 'dashboards#pot', as: 'dashboard_pot'
  get '/dashboard/health', to: 'dashboards#health', as: 'dashboard_health'
  get '/dashboard/motivation', to: 'dashboards#motivation', as: 'dashboard_motivation'
  # get '/dashboard/new_transaction', to: 'dashboards#new_transaction', as: 'dashboard_new_transaction'
  # post '/dashboard/new_transaction', to: 'dashboards#create_new_transaction', as: 'dashboard_create_new_transaction'
  resources :transactions, only: [:new, :create]
  get '/profile', to: 'profiles#profile_home', as: 'profile_home'
  get '/profile/edit/profile_info', to: 'profiles#profile_info', as: 'profile_info'
  # edit_user_registration GET    /users/edit(.:format)

  # user_registration PATCH  /users(.:format)
  get '/profile/edit/profile_bank', to: 'profiles#edit_profile_bank', as: 'profile_bank'
  patch '/profile/edit/profile_bank', to: 'profiles#update_profile_bank'
  #consumptions POST   /consumptions(.:format) consumptions#create
  # new_consumption GET    /consumptions/new(.:format) consumptions#new
  get '/get_my_pot', to: 'profiles#recover_my_pot', as: 'recover_my_pot'
  patch '/get_my_pot', to: 'profiles#withdraw', as: 'withdraw'
  get '/profile/edit/avatar', to: 'profiles#avatar_base', as: 'avatar'
  patch '/profile/edit/avatar', to: 'profiles#avatar', as: 'update_avatar'

end

app/views/pages/home.html.erb
<div class="background-home">
  <div class="home-logo">
    <%= image_tag("Logo1.png", style: {height: ": 60px"})%>
  </div>
  <div class="slogan-container">
    <p class="slogan">Vous n’allez pas croire tout ce que vous allez économiser. </p>
  </div>
  <%= link_to "ME CONNECTER 👋", login_path, class: "btn connect-button" %> <br>
  <%= link_to "Découvrir l'app", simulation_path, class: "home-link" %>
</div>

app/views/pages/login.html.erb
<div class="container">
    <div class="back-arrow">
      <%= link_to 'Back', onclick: "window.history.back();", id: "icone-arrow" do %>
        <i class="iconify" data-icon="akar-icons:arrow-left"></i>
      <% end %>
    </div>

    <div class="my-inscription-h1" >
      <h1>Connexion</h1>
    </div>

    <div class="my-profile-p" >
      <p>Connectez-vous simplement</p>
    </div>

    <div class ="icone-profile" style="text-align: center;">
      <span class="iconify" data-icon="carbon:user-avatar"></span>
    </div>

    <div class="btn-apple">
      <span class="iconify" data-icon="ant-design:apple-filled" style="color: white; height: 26px; width: 22px"></span>
      <p> Continuer avec Apple</p>
    </div>

    <div class="btn-facebook">
      <span class="iconify" data-icon="akar-icons:facebook-fill" style="color: white;"></span>
      <p> Continuer avec Facebook</p>
    </div>

    <div class="btn-google">
      <span class="iconify" data-icon="flat-color-icons:google" style="color: white;"></span>
      <p> Continuer avec Google</p>
    </div>

    <div class="btn-mail">
      <span class="iconify" data-icon="carbon:email" style="color: white;"></span>
      <% if params[:discover] == "true" %>
        <%= link_to 'Continuer avec mon email', new_user_registration_path, class:"continue-with-email" %>
        <% elsif params[:discover] == nil %>
      <%= link_to 'Continuer avec mon email', new_user_session_path, class:"continue-with-email" %>
    <% end %>
    </div>

</div>

app/views/pages/new_objective.erb
<div class="conso-container">
  <div class="header-pink">
    <h1 class="consommation-title">Objectif</h1>
  </div>

  <div class="cig-img">
    <%= image_tag("target.png", style: {height: ": 100px"})%>
  </div>

  <p class="conso-asking">Quel est votre projet avec l’argent économisé de vos cigarettes ?</p>

  <div class="new-objective">
    <div class="form-input-with">
      <%= form_with url: create_objective_path, method: :post do |f| %>
        <%= f.label :query, "Quel est votre objectif :" %>
      <div class="form-with-control-empty">
        <%= f.text_field :objective_title %>
      </div>
        <%= f.label :query, "Quel est le budget de votre objectif :" %>
      <div class="form-with-control-empty">
        <%= f.text_field :objective_amount, required: 'required' %>
      </div>
    </div>
    <br>
    <br>
    <br>
    <div class="form-action-with">
        <%= f.submit "Valider", class:"green-btn" %>
      <% end %>
    </div>
  </div>

</div>

app/views/pages/result.html.erb
<% result = @result.sample %>
<div class="backgorund-img-result" style="background-image: url(<%= result[:background] %>)">
  <div class="back-arrow">
    <%= link_to 'Back', onclick: "window.history.back();", id: "icone-arrow" do %>
      <i class="iconify" data-icon="akar-icons:arrow-left"></i>
    <% end %>
  </div>
</div>
<div class="card-result">
  <p class="result-sentence">Avec ce budget, vous auriez pu vous <br> accorder :</p>
  <h2 class="result-title"><%= result[:title] %></h2>
  <div class="arrow">
    <img src="assets/arrow" alt="">
  </div>
  <p class="budget"><%= @cost.round %>€</p>
  <div class="detail-cost">
    <p>Coût par mois: <%= (@cost / 12).round %>€</p>
    <p>Coût par an: <%= @cost.round  %>€</p>
    <p>Coût sur 10 ans: <%= (@cost * 10).round %>€</p>
    <p>Coût sur 30 ans: <%= (@cost * 30).round %>€</p>
  </div>
  <div class="button-container-result">
    <%= link_to("Commencer à cagnotter", login_path(discover: true), class: "btn-begin-pot", ) %>
  </div>
</div>

app/views/pages/show_objective.erb
<div class="background-img-objective"></div>
<div class="card-result">
  <p class="result-sentence">Un peu de volonté pour un projet<br>qui te tient à coeur :</p>
  <h2 class="result-title"> <%= current_user.objective_title %></h2>
  <div class="arrow-objective">
    <p id="start-j"><strong>J-1</strong></p>
    <img src="/assets/arrow-j" alt="">
    <p id="end-j"><strong>J-<%= current_user.objective_duration %></strong></p>
  </div>
  <p class="budget"> <%= current_user.objective_amount %>€</p>
  <p class="result-sentence">Dans <%= current_user.objective_duration%> jours, tu auras économisé <%= current_user.objective_amount%>€ en<br>évitant d'acheter <%= current_user.objective_number_of_packs %> paquets soit <%= current_user.objective_number_of_packs * 20 %> cigarettes</p>
</div>


  <%= link_to dashboard_path, class: "text-decoration-none" do %>
  <div class="btn-continuer">
    <p> Continuer</p>
  </div>
  <% end %>

  <div class="logo d-flex justify-content-center mt-4">
    <img style="height : 60px" src="/assets/Logo1.png">
  </div>

<div class="footer_card d-flex align-items-center">
</div>

app/views/pages/simulation.html.erb
<div class="conso-container">
  <div class="header-pink">
    <h1 class="consommation-title">Consommation</h1>
  </div>
  <div class="cig-img">
    <%= image_tag("cigarette.png", style: {height: ": 100px"})%>
  </div>
  <p class="conso-asking">Quelle est votre consommation de cigarettes ?</p>
  <%= render "shared/consommation_form" %>
</div>