config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  authenticated :user do
    root to: "dashboards#dashboard", as: "authenticated_root"
  end
  unauthenticated :user do
    root to: "pages#home"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :consumptions, only: [:new, :create] do
    resources :cigarettes, only: [:create]
  end
  get '/login', to: 'pages#login', as: 'login'
  get '/simulation', to: 'pages#simulation', as: 'simulation'
  get '/result', to: 'pages#result', as: 'result'
  get '/objective/new', to: 'pages#new_objective', as: 'new_objective'
  post '/objective/create', to: 'pages#create_objective', as: 'create_objective'
  get '/objective/show', to: 'pages#show_objective', as: 'show_objective'
  get '/dashboard', to: 'dashboards#dashboard', as: 'dashboard'
  get '/dashboard/pot', to: 'dashboards#pot', as: 'dashboard_pot'
  get '/dashboard/health', to: 'dashboards#health', as: 'dashboard_health'
  get '/dashboard/motivation', to: 'dashboards#motivation', as: 'dashboard_motivation'
  # get '/dashboard/new_transaction', to: 'dashboards#new_transaction', as: 'dashboard_new_transaction'
  # post '/dashboard/new_transaction', to: 'dashboards#create_new_transaction', as: 'dashboard_create_new_transaction'
  resources :transactions, only: [:new, :create]
  get '/profile', to: 'profiles#profile_home', as: 'profile_home'
  get '/profile/edit/profile_info', to: 'profiles#profile_info', as: 'profile_info'
  # edit_user_registration GET    /users/edit(.:format)

  # user_registration PATCH  /users(.:format)
  get '/profile/edit/profile_bank', to: 'profiles#edit_profile_bank', as: 'profile_bank'
  patch '/profile/edit/profile_bank', to: 'profiles#update_profile_bank'
  #consumptions POST   /consumptions(.:format) consumptions#create
  # new_consumption GET    /consumptions/new(.:format) consumptions#new
  get '/get_my_pot', to: 'profiles#recover_my_pot', as: 'recover_my_pot'
  patch '/get_my_pot', to: 'profiles#withdraw', as: 'withdraw'
  get '/profile/edit/avatar', to: 'profiles#avatar_base', as: 'avatar'
  patch '/profile/edit/avatar', to: 'profiles#avatar', as: 'update_avatar'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
<!--    <meta name="viewport" content="width=device-width,initial-scale=1">-->
    <meta name="viewport" content="minimal-ui, width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no; viewport-fit=cover">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Noto+Sans+KR:wght@100;300;400;500&family=Space+Mono&display=swap" rel="stylesheet">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <!--    pwa links-->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>

<!--    meta modal-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'shared/navbar' if current_page?(dashboard_path)%>
    <%= render 'shared/navbar' if current_page?(dashboard_health_path)%>
    <%= render 'shared/navbar' if current_page?(dashboard_pot_path)%>
    <%= render 'shared/navbar' if current_page?(dashboard_motivation_path)%>
    <%= render 'shared/navbar' if current_page?(profile_home_path)%>
    <%= render 'shared/navbar' if current_page?(new_transaction_path)%>
    <%= render 'shared/navbar' if current_page?(recover_my_pot_path)%>
    <%= render 'shared/flashes' %>
    <script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>
    <%= yield %>
  </body>
</html>